// action types
export const SELECT_DATASET = 'SELECT_DATASET'
export const REQUEST_DATA = 'REQUEST_DATA'
export const RECEIVE_DATA = 'RECEIVE_DATA'
export const SET_NSAMPLES = 'SET_NSAMPLES'
export const SET_NFEATURES = 'SET_NFEATURES'
export const SET_RANDOM = 'SET_RANDOM'
export const SET_NCLASSES = 'SET_NCLASSES'

export const HIGHLIGHT_SAMPLE = 'HIGHLIGHT_SAMPLE'
export const UNHIGHLIGHT_SAMPLE = 'UNHIGHLIGHT_SAMPLE'
export const SELECT_SAMPLE = 'SELECT_SAMPLE'
export const UNSELECT_SAMPLE = 'UNSELECT_SAMPLE'
export const UPDATE_SELECTIONS = 'UPDATE_SELECTIONS'

export const REQUEST_LINKS = 'REQUEST_LINKS'
export const RECEIVE_LINKS = 'RECEIVE_LINKS'
export const SHOW_LINKS = 'SHOW_LINKS'
export const HIDE_LINKS = 'HIDE_LINKS'

export const SHOW_TOOLTIP = 'SHOW_TOOLTIP'
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP'
export const TOOLTIP_CONTENT = 'TOOLTIP_CONTENT'

export const SELECT_FILTER = 'SELECT_FILTER'
export const REQUEST_FILTER = 'REQUEST_FILTER'
export const RECEIVE_FILTER = 'RECEIVE_FILTER'

export const SELECT_PROJECTION = 'SELECT_PROJECTION'
export const REQUEST_PROJECTION = 'REQUEST_PROJECTION'
export const RECEIVE_PROJECTION = 'RECEIVE_PROJECTION'

export const SELECT_F_PROJECTION = 'SELECT_F_PROJECTION'
export const REQUEST_F_PROJECTION = 'REQUEST_F_PROJECTION'
export const RECEIVE_F_PROJECTION = 'RECEIVE_F_PROJECTION'

export const REQUEST_F_DATA = 'REQUEST_F_DATA'
export const RECEIVE_F_DATA = 'RECEIVE_F_DATA'

export const REQUEST_METRICS = 'REQUEST_METRICS'
export const RECEIVE_METRICS = 'RECEIVE_METRICS'

export const REQUEST_F_METRICS = 'REQUEST_F_METRICS'
export const RECEIVE_F_METRICS = 'RECEIVE_F_METRICS'
